name: multistockfish
description: "Multiple flavors of Stockfish Engine"
version: 0.3.0
repository: https://github.com/lichess-org/dart-multistockfish.git
homepage: https://github.com/lichess-org/dart-multistockfish.git

resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  logging: ^1.3.0
  plugin_platform_interface: ^2.0.2
  multistockfish_sf16: ^0.1.0
  multistockfish_chess: ^0.2.0
  multistockfish_variant: ^0.1.0
  # multistockfish_sf16:
  #   path: ../multistockfish_sf16
  # multistockfish_chess:
  #   path: ../multistockfish_chess
  # multistockfish_variant:
  #   path: ../multistockfish_variant

dev_dependencies:
  fake_async: ^1.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
